source_name: test-agent-maksym
# 10s 20m 1h
interval: 30s
# Enable or disable metric collecting entities
cpu: true
memory: true
# NEVER change <host_identificator> manually.
# It is generated autumaticallly by Agent.
# It provides uniqness of you Agent Collector.
host_id: 0
