source_name: test-agent-maksym
# 10s 20m 1h
interval: 30s
# Enable or disable metric collecting entities
cpu: true
memory: true
# NEVER change <host_identificator> manually.
# It is generated automaticallly by Agent.
# It provides uniqness of you Agent Collector.
# If this value is 0 agent will generate the new host_id
host_id: 0
